# Generated by Django 5.1 on 2024-08-27 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('budget', models.IntegerField()),
                ('message', models.TextField()),
                ('messenger_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_backend_app.messengertypes')),
            ],
        ),
    ]
