# Generated by Django 5.1 on 2024-08-27 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landing_backend_app.servicetypes'),
        ),
    ]
