# Generated by Django 5.1 on 2024-08-27 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_backend_app', '0002_orders_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='messenger_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landing_backend_app.messengertypes'),
        ),
    ]
